-- Inscrições de Web Push — o aparelho que recebe o aviso de fechamento novo.
--
-- Tabela nova em vez de reaproveitar `PushToken`: aquela nasceu para Expo
-- (coluna `expo_push_token`, de um app React Native que nunca existiu), suas
-- policies exigem `auth.uid()`, e os PWAs rodam como `anon`. Ela está vazia —
-- zero linhas — e fica onde está até alguém decidir removê-la.
--
-- O que o navegador entrega ao `pushManager.subscribe()` são três coisas: a URL
-- do serviço de push do fabricante (Apple, no iPhone do dono), e duas chaves
-- que cifram o conteúdo. É isso que guardamos, nada além.
BEGIN;

CREATE TABLE IF NOT EXISTS public."InscricaoPush" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- URL do serviço do fabricante. É a identidade da inscrição: o mesmo
    -- aparelho reinscrito devolve o mesmo endpoint, e é por ele que se
    -- reconhece duplicata.
    endpoint text NOT NULL UNIQUE,
    p256dh text NOT NULL,
    auth text NOT NULL,
    -- Sem login não há a quem vincular. O papel diz para quem o aviso serve;
    -- hoje só o dono, mas a coluna evita ter que migrar quando o frentista
    -- também passar a receber.
    papel text NOT NULL DEFAULT 'dono',
    descricao_aparelho text,
    -- Desligada pela Edge Function quando o serviço do fabricante responde
    -- 404/410: inscrição morta (app desinstalado, permissão revogada).
    ativa boolean NOT NULL DEFAULT true,
    criada_em timestamptz NOT NULL DEFAULT now(),
    usada_em timestamptz
);

CREATE INDEX IF NOT EXISTS idx_inscricaopush_ativa ON public."InscricaoPush" (papel, ativa);

ALTER TABLE public."InscricaoPush" ENABLE ROW LEVEL SECURITY;

-- O `anon` SÓ insere. Não lê, não altera, não apaga.
--
-- Sem SELECT de propósito: a lista de endpoints não precisa sair do servidor —
-- o app descobre se já está inscrito pelo próprio navegador
-- (`pushManager.getSubscription()`), sem consultar o banco. Deixar a leitura
-- aberta entregaria a lista de aparelhos do dono a qualquer um com a `anon key`,
-- que é pública por natureza. A Edge Function lê com `service_role`, que passa
-- por cima da RLS.
DROP POLICY IF EXISTS "Anon pode se inscrever no push" ON public."InscricaoPush";
CREATE POLICY "Anon pode se inscrever no push"
    ON public."InscricaoPush" FOR INSERT TO anon
    WITH CHECK (true);

COMMENT ON TABLE public."InscricaoPush" IS
    'Inscrições de Web Push (padrão do navegador, sem Firebase). Escrita por anon, lida só pela Edge Function.';

COMMIT;
